"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const AuthenticateAccessOrRefreshTokens_1 = require("../../../../middlewares/AuthenticateAccessOrRefreshTokens");
const CheckValidationErrors_1 = require("../../../../middlewares/CheckValidationErrors");
const SSD_1 = require("../../../../controllers/Admin/SSD/SSD");
const SsdValidator_1 = require("./Validator/SsdValidator");
const router = (0, express_1.Router)();
router.get('/get-all', AuthenticateAccessOrRefreshTokens_1.checkUserIsAdmin, SSD_1.getAllSSDController);
router.get('/get-to-delete', AuthenticateAccessOrRefreshTokens_1.checkUserIsAdmin, SSD_1.getAllSSDItemsForDeleteController);
router.post('/insert', SsdValidator_1.insertSSDValidator, AuthenticateAccessOrRefreshTokens_1.checkUserIsAdmin, CheckValidationErrors_1.checkErrors, SSD_1.insertSSDProductController);
router.patch('/modify', SsdValidator_1.insertSSDValidator, AuthenticateAccessOrRefreshTokens_1.checkUserIsAdmin, CheckValidationErrors_1.checkErrors, SSD_1.modifySSDProductController);
router.delete('/delete', AuthenticateAccessOrRefreshTokens_1.checkUserIsAdmin, SSD_1.deleteSSDProductByIdController);
module.exports = router;
